In [1]:
import pandas as pd
from scipy import sparse
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

from CFUserUser import CFUserUser
content = pd.read_csv('lightfm/content_similarity_D2.csv')
records = pd.read_pickle('lightfm/historical_records.pkl')
records['whens'] = pd.to_datetime(records['whens'])
historical_records = records.sort_values('whens')
user_project_matrix_val = pd.read_csv(f'lightfm/user_project_matrix_D2.csv')
data_items_train = pd.read_csv(f'lightfm/data_items_train.csv')
data_items_test = pd.read_csv(f'lightfm/data_items_test.csv')
data_items_train.columns = data_items_train.columns.astype(int)
data_items_test.columns = data_items_test.columns.astype(int)
user_project_matrix_val.reset_index(inplace=True, drop=True)
data_items_train.reset_index(inplace=True, drop=True)
data_items_test.reset_index(inplace=True, drop=True)

In [3]:
project_user =  data_items_train.T
data_items_train = project_user[project_user.sum(axis=1)>2].T
data_items_train

,91,114,3171,97,94,75,1025,151,167,3482,...,157,3834,1673,3829,3823,5255,5127,3830,3826,5351
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11219,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11220,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11221,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11222,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11223,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [1]:
project_user.mean(axis=0)

NameError: name 'project_user' is not defined

In [93]:
project_user[project_user.sum(axis=1)<2]

,0,1,2,3,4,5,6,7,8,9,...,11214,11215,11216,11217,11218,11219,11220,11221,11222,11223
186,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1034,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1768,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
768,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
427,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
769,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
585,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
443,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1044,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
103,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
174,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
445,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3048,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
367,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3253,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2339,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1797,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3475,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3478,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3553,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3602,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2981,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3870,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4956,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3240,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2816,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5144,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4988,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
206,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1630,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5121,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3243,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5316,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3825,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
192,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3477,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5326,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1761,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5343,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1328,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5400,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1218,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [97]:
mean_interat = data_items_train.T.mean(axis=0)
mean

In [104]:
project_user.loc[data_items_train.T.sum(axis=1)<2] = mean_interations

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [100]:
project_user

,0,1,2,3,4,5,6,7,8,9,...,11214,11215,11216,11217,11218,11219,11220,11221,11222,11223
91,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
114,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
94,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5343,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1328,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5400,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1847,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1218,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
data_sparse = sparse.csr_matrix(data_items_train.values.astype(np.float))
similarities = cosine_similarity(data_sparse.transpose())
sim = pd.DataFrame(similarities, data_items_train.columns, data_items_train.columns)
sim.columns = [int(i) for i in sim.columns]
sim.index = [int(i) for i in sim.index]

In [5]:
des = sim.describe()

In [6]:
des =des.T
des

      count      mean       std  min       25%       50%       75%  max
91    122.0  0.040408  0.090687  0.0  0.014929  0.030542  0.046176  1.0
114   122.0  0.040974  0.091386  0.0  0.016408  0.030928  0.046160  1.0
3171  122.0  0.019347  0.091157  0.0  0.000000  0.000000  0.021904  1.0
97    122.0  0.023567  0.089912  0.0  0.007436  0.014751  0.023354  1.0
94    122.0  0.021316  0.089918  0.0  0.006387  0.011560  0.017658  1.0
...     ...       ...       ...  ...       ...       ...       ...  ...
5255  122.0  0.011552  0.092031  0.0  0.000000  0.000000  0.000000  1.0
5127  122.0  0.060253  0.111682  0.0  0.000000  0.016309  0.082005  1.0
3830  122.0  0.066790  0.135085  0.0  0.000000  0.003337  0.072101  1.0
3826  122.0  0.029019  0.111040  0.0  0.000000  0.000000  0.000000  1.0
5351  122.0  0.022096  0.096436  0.0  0.000000  0.000000  0.000000  1.0

[122 rows x 8 columns]

In [7]:
sum(des['max'])

121.99999999999999

In [8]:
sim.loc[92].sort_values(ascending=False)[:11]

92      1.000000
172     0.557244
205     0.053000
119     0.047405
100     0.043274
388     0.037477
1435    0.037477
3025    0.037477
3791    0.037477
1402    0.033520
2794    0.033520
Name: 92, dtype: float64

In [72]:
des['mean'].mean()

0.02552812243198451

In [13]:
content[content['project_id']==172]

,project_id,name,time_per_participation,location_type,project_topic_1,project_topic_2,description,tags,Unnamed: 8,Unnamed: 9
1093,172,GLOBE Observer: Clouds,250,ANY,Earth & Life Sciences,Geology & Earth Science,GLOBE Observer is an international citizen sci...,"['app', 'clouds', 'dust', 'dust storms', 'girl...",NaN,NaN

In [18]:
sim

,91,114,3171,97,94,75,1025,151,167,3482,...,192,5351,3477,5326,1761,5343,1328,5400,1847,1218
91,1.000000,0.081628,0.036769,0.043250,0.033438,0.062344,0.059331,0.027000,0.058979,0.042041,...,0.0,0.027318,0.0,0.0,0.0,0.0,0.061085,0.0,0.0,0.0
114,0.081628,1.000000,0.042899,0.028910,0.025170,0.057585,0.086529,0.024232,0.030359,0.061314,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
3171,0.036769,0.042899,1.000000,0.010655,0.008503,0.020478,0.070157,0.016373,0.006837,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
97,0.043250,0.028910,0.010655,1.000000,0.023442,0.029106,0.040116,0.033101,0.013404,0.020304,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
94,0.033438,0.025170,0.008503,0.023442,1.000000,0.037246,0.022297,0.021014,0.052152,0.024307,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5343,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.0,0.0,0.0,1.0,0.000000,0.0,0.0,0.0
1328,0.061085,0.000000,0.000000,0.000000,0.000000,0.034021,0.000000,0.034001,0.000000,0.000000,...,0.0,0.447214,0.0,0.0,0.0,0.0,1.000000,0.0,0.0,0.0
5400,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,0.0
1847,0.000000,0.000000,0.000000,0.000000,0.000000,0.024056,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,0.0
1218,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1.0

In [9]:
import scipy.spatial.distance as ssd
# convert the redundant n*n square matrix form into a condensed nC2 array
np.fill_diagonal(sim.values, 1)

In [78]:
linkage = hcluster.linkage(distArray)
dendro  = hcluster.dendrogram(linkage)
show()

NameError: name 'hcluster' is not defined

In [15]:
data_items_train

,91,114,3171,97,94,75,1025,151,167,3482,...,157,3834,1673,3829,3823,5255,5127,3830,3826,5351
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11219,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11220,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11221,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11222,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11223,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [55]:
user_project_matrix_val.drop('user',1)

,91,114,3171,97,94,75,1025,151,167,3482,...,192,5351,3477,5326,1761,5343,1328,5400,1847,1218
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11219,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11220,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11221,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11222,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11223,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [83]:
def get_user_projects( user_index):
    known_user_likes = data_items_train.loc[user_index]
    known_user_likes = known_user_likes[known_user_likes > 0].index.values
    return known_user_likes

In [84]:
DF = pd.DataFrame()
df = pd.DataFrame(columns=['User', 'Item', 'Rating'])
for idx, user in data_items_train.iterrows():
    projects = get_user_projects(idx)
    for project in projects:
        df = pd.DataFrame(columns=['User', 'Item', 'Rating'])
        df.loc[0]= idx, project, 1
        DF = pd.concat([DF, df], axis = 0)
DF.reset_index(drop=True)

        User  Item Rating
0          0    91      1
1          1   114      1
2          1  1310      1
3          2    91      1
4          3    97      1
...      ...   ...    ...
13021  11219   153      1
13022  11220    94      1
13023  11221  2992      1
13024  11222   115      1
13025  11223  1310      1

[13026 rows x 3 columns]

In [74]:
from surprise import KNNBasic

from surprise import Reader
from surprise import Dataset
from surprise import accuracy

reader = Reader(rating_scale=(0,1))

data = Dataset.load_from_df(DF[['User', 'Item', 'Rating']], reader)
from surprise.model_selection.split import train_test_split
trainset, testset = train_test_split(data, test_size=0.1)
type(trainset)
# Load the movielens-100k dataset (download it if needed),

algo = KNNBasic()
algo.fit(trainset)

Computing the msd similarity matrix...
Done computing similarity matrix.

In [79]:
predictions = algo.test(testset)
test = pd.DataFrame(predictions)
test = test.rename(columns={'uid':'User', 'iid': 'Item', 
                            'r_ui':'actual', 'est':'prediction'})
cf_model = test.pivot_table(index='User', 
                            columns='Item', values='prediction').fillna(0)

def get_users_predictions(user_id, n, model):
    recommended_items = pd.DataFrame(model.loc[user_id])
    recommended_items.columns = ["predicted_rating"]
    recommended_items = recommended_items.sort_values('predicted_rating', ascending=False)    
    recommended_items = recommended_items.head(n)
    return recommended_items.index.tolist()

def get_recs(model, k):
    recs = []
    for user in model.index:
        cf_predictions = get_users_predictions(user, k, model)
        recs.append(cf_predictions)
    return recs

In [80]:
k = 10
recs = get_recs(cf_model, k)
preds = pd.DataFrame(index=cf_model.index)
preds[f'Top-{k} Recommendation'] = recs
preds

                                  Top-10 Recommendation
User
1     [1310, 1025, 3524, 3834, 3832, 3831, 3830, 382...
4     [92, 1025, 3524, 3834, 3832, 3831, 3830, 3827,...
5     [114, 1025, 3524, 3834, 3832, 3831, 3830, 3827...
6     [2315, 1025, 3472, 3834, 3832, 3831, 3830, 382...
12    [115, 1025, 3524, 3834, 3832, 3831, 3830, 3827...

In [96]:
n_users = DF.User.unique().shape[0]
n_items = DF.Item.unique().shape[0]
data_matrix = np.zeros((n_users, n_items))
for line in DF.head(10).itertuples():
    data_matrix[ line[2]-1,line[1]-1] = line[3]

In [105]:
from sklearn.metrics.pairwise import pairwise_distances 
user_similarity = pairwise_distances(data_items_train, metric='cosine')
item_similarity = pairwise_distances(data_matrix.T, metric='cosine')

In [106]:
def predict(ratings, similarity, type='user'):
    
    if type == 'user':
        #We use np.newaxis so that mean_user_rating has same format as ratings
        
        pred = similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])

In [107]:
user_prediction = predict(data_matrix, user_similarity, type='user')

ValueError: shapes (11224,11224) and (11206,122) not aligned: 11224 (dim 1) != 11206 (dim 0)

In [3]:
explanations_stat = pd.read_csv('explanations_stat_with_content_D3_scaled.csv')

/home/daniel/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (15,23,29,30,33,34,41,45,46,54,60,61,63,64,65,69,71,72,74,75,77,88,90,94,96,97,98,99,100,102,104,106,109,115,116,118,119,136,137,141,143,145,147,149,151,153,158,160,161,172,173,175,176,181,182) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
explanations_stat.head(10)

,91,114,3171,97,94,75,1025,151,167,3482,...,5343,1328,5400,1847,1218,5451,3361,5336,5566,5348
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,item_item,NaN,NaN,popularity,NaN,NaN,NaN,popularity,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,popularity,content,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,content,NaN,content,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,content,popularity,NaN,NaN,NaN,content,content,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,content,content,content,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
from collections import Counter
t = Counter()
for index in range(0,len(explanations_stat)):
    t.update([i for i in explanations_stat.iloc[index].values if i==i])
t

NameError: name 'explanations_stat' is not defined

In [2]:
import numpy as np
def cast_to_list_of_int(lst):
    if lst is not np.nan:
        return [int(p) for p in ast.literal_eval(lst)]

In [1]:
import re
import ast
import pandas as pd
output = pd.read_csv('output_D2_scaled.csv')
output['recommended'] = output['recommended'].apply(lambda x : cast_to_list_of_int(x))
output['popularity'] = output['popularity'].apply(lambda x : cast_to_list_of_int(x))
output['general'] = output['general'].apply(lambda x : cast_to_list_of_int(x))
output['user_user'] = output['user_user'].apply(lambda x : cast_to_list_of_int(x))
output['item_item'] = output['item_item'].apply(lambda x : cast_to_list_of_int(x))
output['associations'] = output['associations'].apply(lambda x : cast_to_list_of_int(x))
output['content'] = output['content'].apply(lambda x : cast_to_list_of_int(x))

output['test'] = output['test'].apply(lambda x : re.sub(r'[\[\]]', '',x).split())

NameError: name 'cast_to_list_of_int' is not defined

In [16]:
def precision_recall_at_k(k):
    results = []
    ip_addresses = ['']
    i=0
    for index, row in output.iterrows():
        precision = np.intersect1d(row['recommended'][:k], row['test']).size / len(row['recommended'][:k])
        recall = np.intersect1d(row['recommended'][:k], row['test']).size / len(row['test'])
        results.append([precision,recall])
    precisions = np.mean([i[0] for i in results if i[0]>=0])
    recalls = np.mean([i[1] for i in results if i[1]>=0])
    return  precisions, recalls
precision_recall_at_k(3)

(0.13078810180926095, 0.390360099881719)

In [17]:
def get_duplicate_values_in_dict(dictionary):
    flipped = {}
    to_return = []
    for key, value in dictionary.items():
        if value not in flipped:
            flipped[value] = [key]
        else:
            flipped[value].append(key)
    flipped = dict(sorted(flipped.items(), key=lambda item: item[1]))
    for key, value in flipped.items():
        if len(value) > 1:
            to_return.extend(value)
    return to_return


def get_best_order(idx, base_order=['item_item', 'user_user', 'content']):
    recs = output.iloc[idx]['recommended']
    i = 0
    best_order = {}
    for alg in base_order:
        project_list = output.iloc[idx][alg]
        if project_list:
            best_order[alg] = recs.index(project_list[0])
    best_order = dict(sorted(best_order.items(), key=lambda item: item[1]))
    return list(best_order.keys())


def get_kendal_lvinstain_from_ordered_list(idx, list_ordered):
    """
    :param idx:
    :param list_ordered:
    :return:
    """
    recs = output.iloc[idx]['recommended']
    explained_recs = []
    for alg in list_ordered:
        if output.iloc[idx][alg]:
            explained_recs.extend(output.iloc[idx][alg])
    if len(recs) != len(explained_recs):
        print("you have a bug!!!!")
#     kendal = (kendalltau(recs, explained_recs)[0] + 1) / 2
#     lvinstain = normalized_damerau_levenshtein_distance(recs, explained_recs)
    return explained_recs

def get_display_order_list(idx):
    output_order = ['associations']
    output_order.extend(get_best_order(idx))
    output_order.extend(get_best_order(idx,['popularity', 'general']))
    return get_kendal_lvinstain_from_ordered_list(idx, output_order)


def get_optimal_order_list(idx):
    """
    :param idx:
    :return: list_ordered
    """
    output_order = ['associations', 'content', 'item_item', 'user_user', 'popularity', 'general']
    output_order = get_best_order(idx, output_order)
    return get_kendal_lvinstain_from_ordered_list(idx, output_order)


def get_larger_size_order_list(idx):
    explain_algs = ['associations', 'content', 'item_item', 'user_user', 'popularity', 'general']
    explain_size_dict = {}
    for alg in explain_algs:
        if output.iloc[idx][alg]:
            explain_size_dict[alg] = len(output.iloc[idx][alg])
    explain_size_dict = dict(sorted(explain_size_dict.items(), reverse=True, key=lambda item: item[1]))
    duplicate_to_sort = get_duplicate_values_in_dict(explain_size_dict)
    explain_size_list = explain_size_dict.keys()
    explain_size_list = list(explain_size_list)
    # if we have the same size, we prefer the order that closest to the optimal
    if len(duplicate_to_sort) > 0:
        sorted_list = get_best_order(idx, duplicate_to_sort)
        opt = explain_size_list.copy()
        for i in range(len(duplicate_to_sort)):
            opt[explain_size_list.index(duplicate_to_sort[i])] = sorted_list[i]
        return get_kendal_lvinstain_from_ordered_list(idx, opt)
    return get_kendal_lvinstain_from_ordered_list(idx, explain_size_list)


def kendal_lvinstain(order_function):
    results = []
    for index, row in output.iterrows():
        kendal, lvinstain = order_function(index)
        results.append([kendal, lvinstain])
    kendal = np.mean([i[0] for i in results if i[0] >= 0])
    lvinstain = np.mean([i[1] for i in results if i[1] >= 0])
    return kendal, lvinstain

In [18]:
output.loc[0]

general                                                [175, 439]
item_item                                                   [723]
popularity                                                  [171]
recommended     [151, 175, 723, 97, 1025, 131, 106, 172, 439, ...
test                                                       [3171]
user                         96260f34-2fb3-567d-b3cc-eabb230b449d
user_user                          [151, 97, 1025, 131, 106, 172]
associations                                                 None
content                                                      None
Name: 0, dtype: object

In [19]:
def add_method_user_index(lst,method, user, index):
    lst.insert(0,method)
    lst.insert(0,user)
    lst.insert(0,index)
    return lst


def get_project_explainer(user, project):
    for alg, lst in output[output['user']==user].iloc[0].to_dict().items():
        if isinstance(lst, list):
            if project in lst and alg !='recommended':
                return str(int(project)) + f"({alg[0]})"
get_project_explainer('96260f34-2fb3-567d-b3cc-eabb230b449d', 439)

'439(g)'

In [20]:
def get_data():
    df = pd.DataFrame()
    i = 0 
    for index, row, in output.iterrows():
        user = output.iloc[index]['user']
        # test:
        test = output.iloc[index]['test'].copy()
        test_series = pd.Series(add_method_user_index(test,'test',user, i))
        df = df.append(test_series, ignore_index=True)
        # alg
        recommended = output.iloc[index]['recommended'].copy()
        recommended_series = pd.Series(add_method_user_index(recommended,'recommended',user, i))
        df = df.append(recommended_series, ignore_index=True)
        # leader 
        leader = get_optimal_order_list(index)
        leader_series = pd.Series(add_method_user_index(leader,'leader',user, i))
        df = df.append(leader_series, ignore_index=True)
        # size 
        size = get_larger_size_order_list(index)
        size_series = pd.Series(add_method_user_index(size,'size',user, i))
        df = df.append(size_series, ignore_index=True)
        # explain_priority 
        exp_priority = get_display_order_list(index)
        exp_priority_series = pd.Series(add_method_user_index(exp_priority,'exp_priority',user, i))
        df = df.append(exp_priority_series, ignore_index=True)
        i+=1
    return df

In [21]:
test = get_data()
for i, row_value in test.iterrows():
    for col in test.columns[3:]:
        p = row_value[col]
        if not pd.isnull(p):
            user = row_value[1]
            test.loc[i,col] = get_project_explainer(user, p)
test

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.0,96260f34-2fb3-567d-b3cc-eabb230b449d,test,3171(t),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,96260f34-2fb3-567d-b3cc-eabb230b449d,recommended,151(u),175(g),723(i),97(u),1025(u),131(u),106(u),172(u),439(g),171(p),NaN
2,0.0,96260f34-2fb3-567d-b3cc-eabb230b449d,leader,151(u),97(u),1025(u),131(u),106(u),172(u),175(g),439(g),723(i),171(p),NaN
3,0.0,96260f34-2fb3-567d-b3cc-eabb230b449d,size,151(u),97(u),1025(u),131(u),106(u),172(u),175(g),439(g),723(i),171(p),NaN
4,0.0,96260f34-2fb3-567d-b3cc-eabb230b449d,exp_priority,151(u),97(u),1025(u),131(u),106(u),172(u),723(i),175(g),439(g),171(p),NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10865,2173.0,69c75e6d-f09b-5f21-a148-8fba0985af94,test,151(t),115(t),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10866,2173.0,69c75e6d-f09b-5f21-a148-8fba0985af94,recommended,75(c),439(c),217(g),1811(c),150(i),171(p),106(i),87(c),3836(i),3611(c),NaN
10867,2173.0,69c75e6d-f09b-5f21-a148-8fba0985af94,leader,75(c),439(c),1811(c),87(c),3611(c),217(g),150(i),106(i),3836(i),171(p),NaN
10868,2173.0,69c75e6d-f09b-5f21-a148-8fba0985af94,size,75(c),439(c),1811(c),87(c),3611(c),150(i),106(i),3836(i),217(g),171(p),NaN
10869,2173.0,69c75e6d-f09b-5f21-a148-8fba0985af94,exp_priority,75(c),439(c),1811(c),87(c),3611(c),150(i),106(i),3836(i),217(g),171(p),NaN

In [28]:
test.to_csv('explanations_order_D2_standardized.csv',index=False)

In [124]:
# print(f"kendalltau : {kendalltau([1,2],[2,1])}")
from sklearn.metrics import ndcg_score
print(ndcg_score([np.argsort([1,2,3,4,5,6,7,8,9,10])], [np.argsort([2,1,3,4,5,6,7,8,9,10])],ignore_ties=True))
print(ndcg_score([np.argsort([1,2,3,4,5,6,7,8,9,10])], [np.argsort([1,2,3,4,5,6,7,8,10,9])],ignore_ties=True))
print(ndcg_score([np.asarray([1,2,3,4,5,6,7,8,9,10])], [np.asarray([2,1,3,4,5,6,7,8,9,10])],ignore_ties=True))
print(ndcg_score([np.asarray([100,2,3,4,5,6,7,8,9,10])], [np.asarray([100,2,3,4,5,6,7,8,10,9])],ignore_ties=True))

# ndcg_score(np.argsort([1,2,3,4,5]), np.argsort([1,2,3,80,75]))

0.999529348181514
0.9854825637977803
0.9996007099471376
0.998939923043521

In [21]:
df = pd.DataFrame(columns=['Hybrid', 'size', 'leader','exp_priority'])
df.append({'foo':1, 'bar':2}, ignore_index=True)

     0 Hybrid exp_priority leader size
0  1.0    NaN          NaN    NaN  NaN
1  2.0    NaN          NaN    NaN  NaN
2  3.0    NaN          NaN    NaN  NaN
3  4.0    NaN          NaN    NaN  NaN

In [12]:
a = pd.DataFrame()